### ISSUE TITLE
Error in raw-socket

### ISSUE THREAD

**Issue by ecoen66** [vectronic/homebridge-ping-hosts#12]
This began showing up recently  - possibly after the upgrade to homebridge 1.3...

/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
             ^
Error: Operation not permitted
    at new Socket (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/net-ping/index.js:147:20)
    at new Session (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/node_modules/net-ping/index.js:545:9)
    at PingHostContactAccessory.doPing (/homebridge/node_modules/@vectronic/homebridge-ping-hosts/index.js:110:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by ecoen66** [comment]
Apologies.  I'm trying the fix from the Read.me
