### ISSUE TITLE
Error at loading when using Node v14.16.0

### ISSUE THREAD

**Issue by Nisse57** [vectronic/homebridge-ping-hosts#13]
I updated Node from v12 to version 14.16.0 and are now getting the below error messages at startup. I'm using HOOBS version 3.3.3. on a RPi4.

3/8/2021, 3:25:49 PM - Error loading plugin "@vectronic/homebridge-ping-hosts"
3/8/2021, 3:25:49 PM - Error: The module '/home/hoobs/.hoobs/node_modules/raw-socket/build/Release/raw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/raw-socket/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/net-ping/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
3/8/2021, 3:25:49 PM - Loaded plugin '@vectronic/homebridge-ping-hosts'

**Comment by vectronic** [comment]
Sorry, missed this previously!

As the message says:

"Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install)."
