### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by dkerr64** [vectronic/homebridge-ping-hosts#23]
Got the following while trying to install on a recently installed homebridge 

```
USER: david
DIR: /usr
CMD: sudo -E -n npm install -g @vectronic/homebridge-ping-hosts@3.1.4

(################⠂⠂) ⠹ reify:@vectronic/homebridge-ping-hosts: http fetch GET 200 http
> raw-socket@1.7.0 install
> node-gyp rebuild

gyp ERR! build error ⠇ reify:@network-utils/arp-lookup: http fetch GET 200 https://reg
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@vectronic/homebridge-ping-hosts/node_modules/raw-socket
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/@vectronic/homebridge-ping-hosts/node_modules/raw-socket
npm ERR! command failed
npm ERR! command sh /tmp/install-c75fdf90.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2022-08-29T14_56_26_499Z-debug-0.log

Operation failed. Please review log for details.
```

Useful system info...

```
Ubuntu Jammy Jellyfish (22.04.1 LTS)
ubuntu-2204
192.168.17.209
fd13:55fe:be36:2::d1
v16.17.0
david
/var/lib/homebridge
/var/lib/homebridge/config.json
```

**Comment by dkerr64** [comment]
It looks like the problem is raw-socket...

```
$ sudo npm install -g raw-socket
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/raw-socket
npm ERR! command failed
npm ERR! command sh /tmp/install-99feb5f4.sh
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/raw-socket/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/raw-socket',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 5.15.0-46-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/raw-socket
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-29T15_19_54_300Z-debug-0.log
```

**Comment by vectronic** [comment]
Hello,

I hit this error as well due to a Node upgrade.

I have modified the plugin to no longer rely on the node-net-ping module and therefore the raw-socket module.

Instead I am now using https://github.com/danielzzz/node-ping which makes use of the native platform's ping tool.

Try version 3.2.0 and see how it goes. 

Unfortunately I am hitting this issue currently so can't fully test the new version: https://github.com/vectronic/homebridge-ping-hosts/issues/23

**Comment by dkerr64** [comment]
I can confirm that I am able to install the plugin.  Now I have to test that it does what I need it for... monitor that a VPN connection to a remote host is alive by pinging it's IP address... and notifying me when the pings fail (suggesting that the VPN has dropped or something else wrong with the connection).
Thanks.
